ALCOOL (id, nom, précision, date_fabrication)
SOFT (id, nomSoft)
INGREDIENT (id, nomIngredient)
COCKTAIL (id, nom, ALCOOL, SOFT, qt_alc, qt_soft, INGREDIENT)
BAR (id, Nom, localisation, COCKTAIL)
User (id, email, password, admin=false)